# Pandas example 1: Wine

The [Wine dataset from UCI machine learning repository](https://archive.ics.uci.edu/dataset/186/wine+quality) contains chemical analysis results from various Portugues wines, together with a numerical "quality" value. We shall have a look at the dataset and try to have a look at how "good" wines differ from "average" wines.

In [4]:
import pandas as pd
df = pd.read_csv('winequality-white.csv',sep=';')
df

,fixed acidity,volatile acidity,citric acid,residual sugar,chlorides,free sulfur dioxide,total sulfur dioxide,density,pH,sulphates,alcohol,quality
0,7.0,0.27,0.36,20.7,0.045,45.0,170.0,1.00100,3.00,0.45,8.8,6
1,6.3,0.30,0.34,1.6,0.049,14.0,132.0,0.99400,3.30,0.49,9.5,6
2,8.1,0.28,0.40,6.9,0.050,30.0,97.0,0.99510,3.26,0.44,10.1,6
3,7.2,0.23,0.32,8.5,0.058,47.0,186.0,0.99560,3.19,0.40,9.9,6
4,7.2,0.23,0.32,8.5,0.058,47.0,186.0,0.99560,3.19,0.40,9.9,6
...,...,...,...,...,...,...,...,...,...,...,...,...
4893,6.2,0.21,0.29,1.6,0.039,24.0,92.0,0.99114,3.27,0.50,11.2,6
4894,6.6,0.32,0.36,8.0,0.047,57.0,168.0,0.99490,3.15,0.46,9.6,5
4895,6.5,0.24,0.19,1.2,0.041,30.0,111.0,0.99254,2.99,0.46,9.4,6
4896,5.5,0.29,0.30,1.1,0.022,20.0,110.0,0.98869,3.34,0.38,12.8,7
4897,6.0,0.21,0.38,0.8,0.020,22.0,98.0,0.98941,3.26,0.32,11.8,6

## Columns

In [6]:
df.columns

Index(['fixed acidity', 'volatile acidity', 'citric acid', 'residual sugar',
       'chlorides', 'free sulfur dioxide', 'total sulfur dioxide', 'density',
       'pH', 'sulphates', 'alcohol', 'quality'],
      dtype='object')

## General statistics

In [5]:
df.describe()

,fixed acidity,volatile acidity,citric acid,residual sugar,chlorides,free sulfur dioxide,total sulfur dioxide,density,pH,sulphates,alcohol,quality
count,4898.000000,4898.000000,4898.000000,4898.000000,4898.000000,4898.000000,4898.000000,4898.000000,4898.000000,4898.000000,4898.000000,4898.000000
mean,6.854788,0.278241,0.334192,6.391415,0.045772,35.308085,138.360657,0.994027,3.188267,0.489847,10.514267,5.877909
std,0.843868,0.100795,0.121020,5.072058,0.021848,17.007137,42.498065,0.002991,0.151001,0.114126,1.230621,0.885639
min,3.800000,0.080000,0.000000,0.600000,0.009000,2.000000,9.000000,0.987110,2.720000,0.220000,8.000000,3.000000
25%,6.300000,0.210000,0.270000,1.700000,0.036000,23.000000,108.000000,0.991723,3.090000,0.410000,9.500000,5.000000
50%,6.800000,0.260000,0.320000,5.200000,0.043000,34.000000,134.000000,0.993740,3.180000,0.470000,10.400000,6.000000
75%,7.300000,0.320000,0.390000,9.900000,0.050000,46.000000,167.000000,0.996100,3.280000,0.550000,11.400000,6.000000
max,14.200000,1.100000,1.660000,65.800000,0.346000,289.000000,440.000000,1.038980,3.820000,1.080000,14.200000,9.000000

## How many of different quality?

In [8]:
df['quality'].value_counts()

quality
6    2198
5    1457
7     880
8     175
4     163
3      20
9       5
Name: count, dtype: int64

## Good, bad, average
We consider a wine to be *average* if its quality is 5 or 6. We consider it *bad* if it's less than 5 and *good* if it's at least 7.

How many wines of different quality?

In [9]:
df_bad = df[df['quality'] < 5]
df_bad.shape

(183, 12)

In [13]:
df_average = df[(df['quality'] == 5) | (df['quality'] == 6)]
df_average.shape

(3655, 12)

In [14]:
df_good = df.query('quality >= 7')
df_good.shape

(1060, 12)

## Small subset of features for good vs. average vs. bad wines

Select a subset of features and compute their means across the different groups of wines to see if there are connections.

In [44]:
df.columns

Index(['fixed acidity', 'volatile acidity', 'citric acid', 'residual sugar',
       'chlorides', 'free sulfur dioxide', 'total sulfur dioxide', 'density',
       'pH', 'sulphates', 'alcohol', 'quality'],
      dtype='object')

In [45]:
features = ['fixed acidity', 'chlorides', 'sulphates', 'alcohol']

In [46]:
df_good[features].mean()

fixed acidity     6.725142
chlorides         0.038160
sulphates         0.500142
alcohol          11.416022
dtype: float64

In [47]:
df_average[features].mean()

fixed acidity     6.876060
chlorides         0.047740
sulphates         0.487557
alcohol          10.269808
dtype: float64

In [48]:
df_bad[features].mean()

fixed acidity     7.180874
chlorides         0.050557
sulphates         0.475956
alcohol          10.173497
dtype: float64

We can also use array operations

In [49]:
df_good[features].mean() - df_bad[features].mean()

fixed acidity   -0.455733
chlorides       -0.012397
sulphates        0.024185
alcohol          1.242525
dtype: float64